# Google Scholar 논문 정보 추출 설정
# Configuration for extracting paper information from Google Scholar

# User-Agent 헤더 (User-Agent header for HTTP requests)
user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
accept_language: 'en-US,en;q=0.9,ko;q=0.8'

# 저자 프로필 URL (Author Profile URL) - plan.md의 목표에 맞게 변경
# 예시: https://scholar.google.com/citations?user=ssXOHSoAAAAJ&hl=en
author_profile_url: 'https://scholar.google.com/citations?user=ssXOHSoAAAAJ&hl=en'

# 테스트용 단일 논문 URL (Test single paper URL for testing)
test_paper_url: 'https://scholar.google.com/citations?view_op=view_citation&hl=en&user=ssXOHSoAAAAJ&sortby=pubdate&citation_for_view=ssXOHSoAAAAJ:XiSMed-E-HIC'

# 출력 파일명 (Output filename)
output_filename: 'test_output.json'

# 출력 디렉토리 (Output directory)
output_dir: 'output'

# 타임아웃 설정 (Request timeout in seconds)
request_timeout: 10

# 페이지네이션 설정 (Pagination settings)
page_size: 100  # 한 번에 가져올 논문 수 (Number of papers to fetch per page)

# 재시도 설정 (Retry settings)
retry_count: 5  # 실패 시 재시도 횟수 (Number of retries on failure)
retry_delay: 10  # 재시도 간 대기 시간(초) (Delay between retries in seconds)
max_retries: 10   # 세션 레벨 최대 재시도 (429/5xx 포함)
backoff_factor: 2.5  # 지수 백오프 계수 (exponential backoff factor)
retry_delay_on_429: 300  # 429 시 대기 시간(초) (우선 Retry-After 헤더 사용)
max_wait_on_block: 1800   # 차단 시 대기 상한(초) (최대 30분)
retry_forever: true       # 성공할 때까지 무한 재시도

# 요청 간 대기 시간 (Delay between requests to avoid server overload)
request_delay: 5    # 초 (seconds)
request_jitter: 3   # 요청 간 랜덤 지터(초) (random jitter added to delay)

# 상태코드 재시도 목록 (Retry on these HTTP status codes)
status_forcelist: [429, 500, 502, 503, 504]
